-- =============================================================================
-- UniGrade — Unilorin Automated Grading System
-- database/schema.sql
--
-- NOTES:
--   - WAL mode and foreign key enforcement are set at the connection level
--     in db_manager.py, NOT here. PRAGMAs in .sql files are ignored by the
--     sqlite3 module when executed via executescript().
--   - All FK relations cascade deletes downward through the hierarchy:
--     lecturers → exams → questions → student_responses
--                       → exam_sessions
--   - student_responses does NOT cascade from students(matric_no) deletion
--     because student records are never deleted (academic integrity).
--   - audit_log.user_id is TEXT to accommodate both matric_no (student) and
--     staff_id string representations (lecturers).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- TABLE: lecturers
-- Stores both Lecturers and Chief Examiners. Role is enforced by CHECK.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lecturers (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    staff_id        TEXT    UNIQUE NOT NULL,
    name            TEXT    NOT NULL,
    department      TEXT,
    email           TEXT    UNIQUE NOT NULL,
    course_code     TEXT,
    course_title    TEXT,
    password_hash   TEXT    NOT NULL,
    role            TEXT    NOT NULL
                            CHECK(role IN ('Lecturer', 'Chief Examiner'))
                            DEFAULT 'Lecturer',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- -----------------------------------------------------------------------------
-- TABLE: exams
-- One exam belongs to one lecturer. Chief Examiner approval tracked here.
-- session_code is unique and auto-generated by application layer.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exams (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    lecturer_id     INTEGER NOT NULL
                            REFERENCES lecturers(id) ON DELETE CASCADE,
    course_code     TEXT    NOT NULL,
    title           TEXT    NOT NULL,
    instructions    TEXT,                           -- Rich text (HTML stored)
    duration        INTEGER NOT NULL,               -- In minutes
    status          TEXT    NOT NULL
                            CHECK(status IN ('Draft', 'Published', 'Closed'))
                            DEFAULT 'Draft',
    session_code    TEXT    UNIQUE,                 -- e.g. "2024-CSC201-MIDTER"
    chief_approved  BOOLEAN NOT NULL DEFAULT FALSE,
    approved_by     INTEGER REFERENCES lecturers(id),
    approved_at     TIMESTAMP,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- -----------------------------------------------------------------------------
-- TABLE: questions
-- Supports hierarchical structure: top-level (parent_question_id IS NULL)
-- and sub-questions (e.g. Q1a, Q1b) via self-referencing FK.
-- Cascade on parent deletion removes all children automatically.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS questions (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id             INTEGER NOT NULL
                                REFERENCES exams(id) ON DELETE CASCADE,
    parent_question_id  INTEGER
                                REFERENCES questions(id) ON DELETE CASCADE,
    question_number     TEXT    NOT NULL,           -- e.g. "1", "1a", "2b"
    question_text       TEXT    NOT NULL,           -- Rich text (HTML)
    model_answer        TEXT    NOT NULL,
    rubric              TEXT    NOT NULL,           -- JSON or freeform text
    max_points          INTEGER NOT NULL,
    is_required         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- -----------------------------------------------------------------------------
-- TABLE: students
-- Matric number is the primary key and authentication token (Phase 1).
-- Records are never deleted (academic integrity constraint).
-- Format: YY/FFDDNNN e.g. "21/52CS001"
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS students (
    matric_no       TEXT PRIMARY KEY,
    name            TEXT,
    department      TEXT NOT NULL,
    level           INTEGER,
    email           TEXT,
    password_hash   TEXT                -- NULL until student sets password on first login
);

-- -----------------------------------------------------------------------------
-- TABLE: student_responses
-- Stores both raw HTML (answer_text) and AI-safe plain text (sanitized_text).
-- Immutable post-submission: only manual_override, overridden_by, and
-- override_reason may be updated by lecturers after status = 'Submitted'.
-- UNIQUE constraint prevents duplicate submissions per question per student.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_responses (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id         INTEGER NOT NULL
                            REFERENCES exams(id) ON DELETE CASCADE,
    student_id      TEXT    NOT NULL
                            REFERENCES students(matric_no),
    question_id     INTEGER NOT NULL
                            REFERENCES questions(id) ON DELETE CASCADE,
    answer_text     TEXT,                           -- Raw HTML from Quill
    sanitized_text  TEXT,                           -- Plain text sent to AI
    ai_score        REAL,
    ai_feedback     TEXT,
    ai_confidence   REAL,                           -- 0.0 to 1.0
    manual_override REAL,                           -- NULL if not overridden
    overridden_by   INTEGER REFERENCES lecturers(id),
    override_reason TEXT,
    submitted_at    TIMESTAMP,
    UNIQUE(exam_id, student_id, question_id)
);


-- -----------------------------------------------------------------------------
-- TABLE: exam_sessions
-- One row per student per exam. Tracks timing, autosave, and submission state.
-- ip_address logged for anti-cheating audit purposes.
-- Resume logic: if status = 'In Progress' and now < end_time, resume session.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exam_sessions (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id         INTEGER NOT NULL
                            REFERENCES exams(id) ON DELETE CASCADE,
    student_id      TEXT    NOT NULL
                            REFERENCES students(matric_no),
    start_time      TIMESTAMP NOT NULL,
    end_time        TIMESTAMP NOT NULL,             -- start_time + duration
    status          TEXT    NOT NULL
                            CHECK(status IN ('In Progress', 'Submitted', 'Auto-Submitted'))
                            DEFAULT 'In Progress',
    last_autosave   TIMESTAMP,
    ip_address      TEXT,
    UNIQUE(exam_id, student_id)
);


-- -----------------------------------------------------------------------------
-- TABLE: audit_log
-- Append-only. Never updated or deleted. Records all sensitive actions:
-- score overrides, approvals, rejections, AI failures.
-- user_id is TEXT to store either a matric_no (student) or staff identifier.
-- exam_id has no FK so audit entries survive exam deletion.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    action      TEXT    NOT NULL,
    user_id     TEXT,                               -- matric_no or staff ref
    exam_id     INTEGER,                            -- no FK: survives exam deletion
    details     TEXT,                               -- JSON string
    timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- =============================================================================
-- INDEXES
-- Created after all tables to avoid forward-reference issues.
-- Targeting the highest-frequency query patterns at peak load.
-- =============================================================================

-- Fetch all responses for a given exam (lecturer review, batch grading)
CREATE INDEX IF NOT EXISTS idx_responses_exam
    ON student_responses(exam_id);

-- Fetch a specific student's responses (results page, resume session)
CREATE INDEX IF NOT EXISTS idx_responses_student
    ON student_responses(student_id);

-- Fetch all questions for an exam (exam hall rendering, grading)
CREATE INDEX IF NOT EXISTS idx_questions_exam
    ON questions(exam_id);

-- Find active sessions at peak load (hundreds of concurrent submissions)
CREATE INDEX IF NOT EXISTS idx_sessions_active
    ON exam_sessions(exam_id, status);